# an example for bigtrack

[hub."hubExample"]
shortLabel = "hubExample"
longLabel = "The trackhub collection for example"
email = "my email"
_genomes = ["exampleGenome"]

[genomes."exampleGenome"]
organism = "A new organism"
scientificName = "The scientific name of the organism"
orderKey = "4800"
defaultPos = "chr1:0-5"
description = "Say something"
_path = "example/genome.fasta"
_groups = ["mapping_and_sequencing"]  # here refers to group_id

[groups."mapping_and_sequencing"]  # here is a group_id
label = "Mapping and Sequencing"  # here is the displayed name
priority = 1
defaultIsClosed = 0

[tracks."bigbed test"]
shortLabel = "bigbed test short"
longLabel = "bigbed test long"
type = "bigBed"
group = "mapping_and_sequencing"
_path = "example/bigbed_test.bed"
