#!/usr/bin/env python3

import os
import sys
import argparse
from src.core import HubCore
from src.utils import *


PROJECT_DIR = os.path.dirname(__file__)
AS_DIR = os.path.join(PROJECT_DIR, "as")


if __name__ == "__main__":

    parser = argparse.ArgumentParser(description="bigtrack")
    parser.add_argument("config", type=str, help="Path to a config file (TOML or JSON)")
    parser.add_argument("-t", "--threads", type=int, default=1, help="Threads [%(default)s]")
    parser.add_argument("-d", "--dryrun", action="store_true", default=False, help="Dry-run mode [%(default)s]")
    parser.add_argument("-f", "--force", action="store_true", default=False, help="Overwrite existing files [%(default)s]")
    args = parser.parse_args()

    print_ascii_art(file=sys.stdout)

    hub_core = HubCore(config_path=args.config, force_overwrite=args.force, dry_run=args.dryrun)

    if not args.dryrun:
        hub_core.execute_jobs(threads=args.threads)
