#!/usr/bin/env python3

import os
import argparse
from src.core import HubCore


PROJECT_DIR = os.path.dirname(__file__)
AS_DIR = os.path.join(PROJECT_DIR, "as")


hub_core = HubCore()
hub_core.parse_configuration_file("example/example.toml")
hub_core.build_hub(force_overwrite=True)
hub_core.hub.generate(dry_run=False)
hub_core.fetch_jobs()
hub_core.print_jobs()
hub_core.execute_jobs(threads=8)
